---
# handlers file for setup-apache
- name: start httpd service
  service:
    name: httpd
    state: started
  when:  ansible_os_family == "RedHat"
    #    tags: start_apache
  ignore_errors: yes

- name: start apache
  service:
    name: apache2
    state: started
  when:  ansible_os_family == "Debian"
- name: restart apache
  service:
    name: httpd
    state: restarted
  when:  ansible_os_family == "RedHat"

- name: restart apache2
  service:
    name: httpd
    state: restarted
  when:  ansible_os_family == "Debian"

