---
- name: installing apache on ubuntu system using ansible
  hosts: all
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    when:  ansible_os_family == "Debian"
    #    tags: install apache

  - name: start apache
    service:
      name: apache2
      state: started
    when:  ansible_os_family == "Debian"
    #    tags: start_apache

  - name: install packages
    yum:
      name: httpd
      state: installed
      #  notify: start httpd service
    when:  ansible_os_family == "RedHat"
    #    tags: install apache

    # handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
    when:  ansible_os_family == "RedHat"  
    #    tags: start_apache
    ignore_errors: yes

  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 666  
