---
- name: installing apache on ubuntu system using ansible
  hosts: dbservers
  become: true
  tasks:
  - name: install apache2
    apt: 
      name: apache2
      state: present
  - name: start apache
    service: 
      name: apache2
      state: started    
