---
- name: installing apache on ubuntu system using ansible
  hosts: all
  become: true
  vars:
    port: 8082
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
    when:  ansible_os_family == "Debian"
    notify: start apache2
    #    tags: install apache

  - name: install packages
    yum:
      name: httpd
      state: installed
    when:  ansible_os_family == "RedHat"
    notify: start httpd service

    #    tags: install apache
  - name: Ensure the default apache port is {{ port }}
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regex: '^Listen '
      insertafter: '^Listen '
      line: Listen {{ port }}
    when:  ansible_os_family == "RedHat"
    notify: restart apache

  - name: Ensure the default apache port is {{ port }} on ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regex: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when:  ansible_os_family == "Debian"
    notify: restart apache2

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
    when:  ansible_os_family == "RedHat"  
    #    tags: start_apache
    ignore_errors: yes

  - name: start apache
    service:
      name: apache2
      state: started
    when:  ansible_os_family == "Debian"
  - name: restart apache
    service:
      name: httpd
      state: restarted
    when:  ansible_os_family == "RedHat"

  - name: restart apache2
    service:
      name: httpd
      state: restarted
    when:  ansible_os_family == "Debian"

    #    tags: start_apache


  - name: copy index.html
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 666  
