---
# tasks file for setup-apache
- name: install apache2
  apt:
    name: apache2
    state: present
  when:  ansible_os_family == "Debian"
  notify: start apache2
    #    tags: install apache

- name: install packages
  yum:
    name: httpd
    state: installed
  when:  ansible_os_family == "RedHat"
  notify: start httpd service

    #    tags: install apache
- name: Ensure the default apache port is {{ port }}
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: '^Listen '
    insertafter: '^Listen '
    line: Listen {{ port }}
  when:  ansible_os_family == "RedHat"
  notify: restart apache

- name: Ensure the default apache port is {{ port }} on ubuntu
  lineinfile:
    path: /etc/apache2/ports.conf
    regex: '^Listen '
    insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
    line: Listen {{ port }}
  when:  ansible_os_family == "Debian"
  notify: restart apache2
- name: copy index.html
  copy:
    src: /opt/ansible/index.html
    dest: /var/www/html
    mode: 666

